fix(*): Update dependencies to resolve security alerts (#2983)
* fix(*): Resolve dependabot security alerts

Resolved alerts:
- follow-redirects https://github.com/clerk/javascript/security/dependabot/233
- nextjs https://github.com/clerk/javascript/security/dependabot/234
- graphql https://github.com/clerk/javascript/security/dependabot/207

* fix(elements): Resolve issue with rollup linux missing dependency

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.