chore(clerk-js): Improve Token.create to handle error due to network failure (#3068)
Error resolved by returning an empty string or null instead of trying to
decode the `jwt` property from the response data. After this fix an
`token.getRawString()` will return an empty string and  `session.getToken()`
will return `null`  on Network failure and when request fails and browser
is offline.

Current error message example:
```
Error: ClerkJS: Token refresh failed (error='Cannot read properties of null (reading 'jwt')')
```